#!/bin/bash

# Railway CLI - Copy & Paste Deploy Script
# This script contains the exact commands you need to deploy
# You can run this line by line, or copy individual commands

echo "🚂 Railway Deployment - Copy & Paste Commands"
echo "=============================================="
echo ""
echo "Step 1: Login to Railway"
echo "------------------------"
echo "railway login"
echo ""

echo "Step 2: Navigate to Backend & Initialize"
echo "----------------------------------------"
echo "cd backend"
echo "railway init"
echo ""

echo "Step 3: Set Essential Environment Variables"
echo "-------------------------------------------"
echo "# Generate a secret key first:"
echo "python3 -c 'import secrets; print(secrets.token_urlsafe(32))'"
echo ""
echo "# Then set variables (replace values with your own):"
echo "railway variables set SECRET_KEY='your-generated-secret-key'"
echo "railway variables set ADMIN_USERNAME='admin'"
echo "railway variables set ADMIN_PASSWORD='your-secure-password'"
echo "railway variables set FRONTEND_URL='https://your-netlify-site.netlify.app'"
echo "railway variables set CORS_ORIGINS='https://your-netlify-site.netlify.app'"
echo ""

echo "Step 4 (Optional): Add PostgreSQL Database"
echo "------------------------------------------"
echo "railway add postgresql"
echo ""

echo "Step 5 (Optional): Configure Email"
echo "----------------------------------"
echo "railway variables set SENDGRID_API_KEY='your-sendgrid-api-key'"
echo "railway variables set EMAIL_FROM='noreply@balmsoothes.com'"
echo ""

echo "Step 6: Deploy!"
echo "--------------"
echo "railway up"
echo ""

echo "Step 7: Get Your Backend URL"
echo "---------------------------"
echo "railway domain"
echo ""

echo "Step 8: View Logs"
echo "----------------"
echo "railway logs --tail"
echo ""

echo "═══════════════════════════════════════"
echo "🎯 Quick Reference"
echo "═══════════════════════════════════════"
echo ""
echo "View environment variables:    railway variables"
echo "Check deployment status:       railway status"
echo "Open Railway dashboard:        railway open"
echo "Run command with Railway env:  railway run <command>"
echo "Redeploy:                      railway up"
echo ""

echo "═══════════════════════════════════════"
echo "📝 After Deployment Checklist"
echo "═══════════════════════════════════════"
echo ""
echo "[ ] Got Railway URL from 'railway domain'"
echo "[ ] Updated frontend/src/config/api.ts with Railway URL"
echo "[ ] Added VITE_API_URL to Netlify environment variables"
echo "[ ] Tested login/register on live site"
echo "[ ] Tested product viewing"
echo "[ ] Tested shopping cart"
echo ""

echo "═══════════════════════════════════════"
echo "🔧 Troubleshooting Commands"
echo "═══════════════════════════════════════"
echo ""
echo "# View real-time logs"
echo "railway logs --tail"
echo ""
echo "# Check if deployment succeeded"
echo "railway status"
echo ""
echo "# Verify environment variables"
echo "railway variables"
echo ""
echo "# Test locally with Railway environment"
echo "railway run uvicorn app.main:app --reload"
echo ""
echo "# Initialize database (if using PostgreSQL)"
echo "railway run python scripts/init_db.py"
echo ""

